/* ============================================================
   200 IDEAS POR HACER JUNTOS
   Agrega, quita o edita libremente. El orden aquí es el orden
   en que aparecen en las hojas.
============================================================ */

const IDEAS = [
  // ---- 🎬 CINE Y PANTALLAS ----
  { cat: "🎬 Cine y pantallas", txt: "Ir al cine a ver un estreno" },
  { cat: "🎬 Cine y pantallas", txt: "Maratón de películas de un mismo director" },
  { cat: "🎬 Cine y pantallas", txt: "Cine en casa con palomitas y luces apagadas" },
  { cat: "🎬 Cine y pantallas", txt: "Ver la primera película que vieron juntos" },
  { cat: "🎬 Cine y pantallas", txt: "Ir a un autocine" },
  { cat: "🎬 Cine y pantallas", txt: "Maratón de una saga completa en un fin de semana" },
  { cat: "🎬 Cine y pantallas", txt: "Elegir la película del otro sin decirle cuál es" },
  { cat: "🎬 Cine y pantallas", txt: "Ver una serie entera juntos" },
  { cat: "🎬 Cine y pantallas", txt: "Ir a una función de medianoche" },
  { cat: "🎬 Cine y pantallas", txt: "Hacer una noche de cine temático (comida del país de la peli)" },

  // ---- 🍝 COMIDA Y COCINA ----
  { cat: "🍝 Comida y cocina", txt: "Ir a un restaurante caro y vestirse elegante" },
  { cat: "🍝 Comida y cocina", txt: "Cocinar una receta nueva juntos" },
  { cat: "🍝 Comida y cocina", txt: "Hacer una cena a la luz de las velas en casa" },
  { cat: "🍝 Comida y cocina", txt: "Ir a un buffet libre y comer hasta no poder más" },
  { cat: "🍝 Comida y cocina", txt: "Probar un restaurante de comida que nunca hayan probado" },
  { cat: "🍝 Comida y cocina", txt: "Hacer pizza casera desde cero" },
  { cat: "🍝 Comida y cocina", txt: "Ir a un mercado de agricultores y cocinar con lo que compren" },
  { cat: "🍝 Comida y cocina", txt: "Hacer un picnic en el parque" },
  { cat: "🍝 Comida y cocina", txt: "Ir a un food truck festival" },
  { cat: "🍝 Comida y cocina", txt: "Hacer sushi juntos en casa" },
  { cat: "🍝 Comida y cocina", txt: "Ir a un restaurante con vista panorámica" },
  { cat: "🍝 Comida y cocina", txt: "Hacer una noche de tapas y vino" },
  { cat: "🍝 Comida y cocina", txt: "Ir a un café literario y quedarse horas" },
  { cat: "🍝 Comida y cocina", txt: "Hacer una cata de chocolates" },
  { cat: "🍝 Comida y cocina", txt: "Ir a un restaurante con menú degustación" },
  { cat: "🍝 Comida y cocina", txt: "Cocinar el uno para el otro (cada uno hace un plato)" },
  { cat: "🍝 Comida y cocina", txt: "Ir a un bar de karaoke y cantar juntos" },
  { cat: "🍝 Comida y cocina", txt: "Hacer una fondue de queso o chocolate" },
  { cat: "🍝 Comida y cocina", txt: "Ir a un restaurante a oscuras" },
  { cat: "🍝 Comida y cocina", txt: "Hacer galletas decoradas juntos" },
  { cat: "🍝 Comida y cocina", txt: "Ir a un brunch dominguero" },
  { cat: "🍝 Comida y cocina", txt: "Hacer una noche de cocina de otro país" },
  { cat: "🍝 Comida y cocina", txt: "Ir a una feria gastronómica" },
  { cat: "🍝 Comida y cocina", txt: "Hacer una competencia de quién cocina mejor" },
  { cat: "🍝 Comida y cocina", txt: "Ir a un restaurante flotante" },
  { cat: "🍝 Comida y cocina", txt: "Hacer helado casero" },
  { cat: "🍝 Comida y cocina", txt: "Ir a un wine tasting" },
  { cat: "🍝 Comida y cocina", txt: "Hacer una cena con los mejores platos de cada uno" },

  // ---- 🧱 JUEGOS Y LEGOS ----
  { cat: "🧱 Juegos y LEGOs", txt: "Armar un set de LEGO juntos" },
  { cat: "🧱 Juegos y LEGOs", txt: "Hacer una noche de juegos de mesa" },
  { cat: "🧱 Juegos y LEGOs", txt: "Armar un rompecabezas de 1000 piezas" },
  { cat: "🧱 Juegos y LEGOs", txt: "Ir a una escape room" },
  { cat: "🧱 Juegos y LEGOs", txt: "Jugar videojuegos cooperativos toda la noche" },
  { cat: "🧱 Juegos y LEGOs", txt: "Ir a una sala de realidad virtual" },
  { cat: "🧱 Juegos y LEGOs", txt: "Jugar cartas con apuestas divertidas (no dinero)" },
  { cat: "🧱 Juegos y LEGOs", txt: "Hacer un torneo de ajedrez o damas chinas" },
  { cat: "🧱 Juegos y LEGOs", txt: "Ir a una feria de juegos de mesa" },
  { cat: "🧱 Juegos y LEGOs", txt: "Inventar un juego de mesa propio" },
  { cat: "🧱 Juegos y LEGOs", txt: "Ir a los bolos" },
  { cat: "🧱 Juegos y LEGOs", txt: "Jugar minigolf" },
  { cat: "🧱 Juegos y LEGOs", txt: "Ir a una sala de arcade" },
  { cat: "🧱 Juegos y LEGOs", txt: "Hacer una noche de trivia" },
  { cat: "🧱 Juegos y LEGOs", txt: "Ir a un casino (solo por la experiencia)" },
  { cat: "🧱 Juegos y LEGOs", txt: "Jugar al air hockey" },
  { cat: "🧱 Juegos y LEGOs", txt: "Hacer un torneo de ping pong" },
  { cat: "🧱 Juegos y LEGOs", txt: "Ir a una feria de atracciones" },
  { cat: "🧱 Juegos y LEGOs", txt: "Jugar a las escondidas en un centro comercial" },
  { cat: "🧱 Juegos y LEGOs", txt: "Hacer una guerra de nerf" },

  // ---- 🏞️ AIRE LIBRE Y NATURALEZA ----
  { cat: "🏞️ Aire libre", txt: "Ir a acampar" },
  { cat: "🏞️ Aire libre", txt: "Ver un atardecer juntos" },
  { cat: "🏞️ Aire libre", txt: "Ver el amanecer juntos" },
  { cat: "🏞️ Aire libre", txt: "Ir a una caminata o senderismo" },
  { cat: "🏞️ Aire libre", txt: "Hacer un picnic bajo las estrellas" },
  { cat: "🏞️ Aire libre", txt: "Ir a la playa" },
  { cat: "🏞️ Aire libre", txt: "Hacer un castillo de arena" },
  { cat: "🏞️ Aire libre", txt: "Ir a un lago y rentar una lancha" },
  { cat: "🏞️ Aire libre", txt: "Hacer kayak o paddle surf" },
  { cat: "🏞️ Aire libre", txt: "Ir a montar bicicleta juntos" },
  { cat: "🏞️ Aire libre", txt: "Visitar un jardín botánico" },
  { cat: "🏞️ Aire libre", txt: "Ir a el mar" },
  { cat: "🏞️ Aire libre", txt: "Hacer una fogata y asar malvaviscos" },
  { cat: "🏞️ Aire libre", txt: "Ir a un mirador nocturno" },
  { cat: "🏞️ Aire libre", txt: "Volar un papalote" },
  { cat: "🏞️ Aire libre", txt: "Ir a un parque de diversiones" },
  { cat: "🏞️ Aire libre", txt: "Hacer un picnic en la montaña" },
  { cat: "🏞️ Aire libre", txt: "Visitar una cascada" },
  { cat: "🏞️ Aire libre", txt: "Ir a un aviario" },
  { cat: "🏞️ Aire libre", txt: "Hacer una noche de camping en el patio" },
  { cat: "🏞️ Aire libre", txt: "Ir a una granja y recoger frutas" },
  { cat: "🏞️ Aire libre", txt: "Hacer una caminata nocturna con linternas" },
  { cat: "🏞️ Aire libre", txt: "Ir a un museo" },
  { cat: "🏞️ Aire libre", txt: "Visitar un volcán o cráter" },
  { cat: "🏞️ Aire libre", txt: "Hacer un tour de árboles o tirolesa" },

  // ---- 🎨 ARTE Y CREATIVIDAD ----
  { cat: "🎨 Arte y creatividad", txt: "Hacer una clase de pintura juntos" },
  { cat: "🎨 Arte y creatividad", txt: "Pintarse el uno al otro" },
  { cat: "🎨 Arte y creatividad", txt: "Hacer una clase de cerámica" },
  { cat: "🎨 Arte y creatividad", txt: "Escribir una carta de amor y leerla en voz alta" },
  { cat: "🎨 Arte y creatividad", txt: "Hacer un álbum de fotos juntos" },
  { cat: "🎨 Arte y creatividad", txt: "Hacer un scrapbook de la relación" },
  { cat: "🎨 Arte y creatividad", txt: "Crear una playlist de canciones que los representen" },
  { cat: "🎨 Arte y creatividad", txt: "Hacer un video de sus mejores momentos" },
  { cat: "🎨 Arte y creatividad", txt: "Escribir un poema o canción el uno para el otro" },
  { cat: "🎨 Arte y creatividad", txt: "Hacer un collage de sueños juntos" },
  { cat: "🎨 Arte y creatividad", txt: "Tomar una clase de fotografía" },
  { cat: "🎨 Arte y creatividad", txt: "Hacer una sesión de fotos juntos" },
  { cat: "🎨 Arte y creatividad", txt: "Crear un mural o grafiti juntos" },
  { cat: "🎨 Arte y creatividad", txt: "Hacer velas artesanales" },
  { cat: "🎨 Arte y creatividad", txt: "Hacer jabones artesanales" },
  { cat: "🎨 Arte y creatividad", txt: "Hacer una clase de manualidades" },
  { cat: "🎨 Arte y creatividad", txt: "Dibujar el uno al otro sin mirar el papel" },
  { cat: "🎨 Arte y creatividad", txt: "Hacer un cómic de su historia" },
  { cat: "🎨 Arte y creatividad", txt: "Escribir un diario juntos" },
  { cat: "🎨 Arte y creatividad", txt: "Hacer una cápsula del tiempo" },
  { cat: "🎨 Arte y creatividad", txt: "Hacer un árbol genealógico de la pareja" },
  { cat: "🎨 Arte y creatividad", txt: "Diseñar juntos algo (una camiseta, un póster)" },
  { cat: "🎨 Arte y creatividad", txt: "Hacer una clase de repostería" },
  { cat: "🎨 Arte y creatividad", txt: "Hacer una clase de coctelería" },
  { cat: "🎨 Arte y creatividad", txt: "Hacer una clase de baile" },

  // ---- 🏃 DEPORTE Y AVENTURA ----
  { cat: "🏃 Deporte y aventura", txt: "Ir a un partido de fútbol o deporte favorito" },
  { cat: "🏃 Deporte y aventura", txt: "Hacer una carrera juntos (5k, 10k)" },
  { cat: "🏃 Deporte y aventura", txt: "Ir a patinar sobre hielo" },
  { cat: "🏃 Deporte y aventura", txt: "Ir a patinar sobre ruedas" },
  { cat: "🏃 Deporte y aventura", txt: "Hacer una clase de yoga juntos" },
  { cat: "🏃 Deporte y aventura", txt: "Ir a escalar (indoor o roca)" },
  { cat: "🏃 Deporte y aventura", txt: "Hacer un día de spa para dos" },
  { cat: "🏃 Deporte y aventura", txt: "Ir a una clase de boxeo o kickboxing" },
  { cat: "🏃 Deporte y aventura", txt: "Hacer una competencia de natación" },
  { cat: "🏃 Deporte y aventura", txt: "Ir a montar a caballo" },
  { cat: "🏃 Deporte y aventura", txt: "Hacer un tour en bicicleta" },
  { cat: "🏃 Deporte y aventura", txt: "Ir a un trampoline park" },
  { cat: "🏃 Deporte y aventura", txt: "Hacer una clase de spinning" },
  { cat: "🏃 Deporte y aventura", txt: "Ir a una clase de defensa personal" },
  { cat: "🏃 Deporte y aventura", txt: "Hacer una carrera de obstáculos" },
  { cat: "🏃 Deporte y aventura", txt: "Ir a un parque de cuerdas altas" },
  { cat: "🏃 Deporte y aventura", txt: "Hacer una sesión de entrenamiento juntos" },
  { cat: "🏃 Deporte y aventura", txt: "Ir a un torneo de paintball" },
  { cat: "🏃 Deporte y aventura", txt: "Hacer una clase de artes marciales" },
  { cat: "🏃 Deporte y aventura", txt: "Ir a un campo de tiro (si les gusta)" },

  // ---- 🎵 MÚSICA Y BAILE ----
  { cat: "🎵 Música y baile", txt: "Ir a un concierto juntos" },
  { cat: "🎵 Música y baile", txt: "Ir a un festival de música" },
  { cat: "🎵 Música y baile", txt: "Bailar en la cocina a medianoche" },
  { cat: "🎵 Música y baile", txt: "Hacer una noche de karaoke en casa" },
  { cat: "🎵 Música y baile", txt: "Ir a una obra de teatro o musical" },
  { cat: "🎵 Música y baile", txt: "Hacer una clase de salsa o bachata" },
  { cat: "🎵 Música y baile", txt: "Ir a un bar de jazz" },
  { cat: "🎵 Música y baile", txt: "Hacer una serenata el uno al otro" },
  { cat: "🎵 Música y baile", txt: "Ir a un karaoke público" },
  { cat: "🎵 Música y baile", txt: "Crear una coreografía juntos" },
  { cat: "🎵 Música y baile", txt: "Ir a una ópera o filarmónica" },
  { cat: "🎵 Música y baile", txt: "Hacer una noche de música en vivo en un bar" },
  { cat: "🎵 Música y baile", txt: "Tocar un instrumento juntos" },
  { cat: "🎵 Música y baile", txt: "Ir a una fiesta temática de los 80s/90s" },
  { cat: "🎵 Música y baile", txt: "Hacer una playlist para cada estado de ánimo" },

  // ---- ✈️ VIAJES Y ESCAPADAS ----
  { cat: "✈️ Viajes y escapadas", txt: "Hacer un viaje de fin de semana a un lugar nuevo" },
  { cat: "✈️ Viajes y escapadas", txt: "Ir a un pueblo mágico" },
  { cat: "✈️ Viajes y escapadas", txt: "Hacer un road trip sin destino fijo" },
  { cat: "✈️ Viajes y escapadas", txt: "Ir a un hotel con todo incluido" },
  { cat: "✈️ Viajes y escapadas", txt: "Acampar en la playa" },
  { cat: "✈️ Viajes y escapadas", txt: "Visitar una ciudad cercana que no conozcan" },
  { cat: "✈️ Viajes y escapadas", txt: "Hacer un viaje en tren" },
  { cat: "✈️ Viajes y escapadas", txt: "Ir a un glamping" },
  { cat: "✈️ Viajes y escapadas", txt: "Visitar un viñedo" },
  { cat: "✈️ Viajes y escapadas", txt: "Hacer un tour gastronómico en otra ciudad" },
  { cat: "✈️ Viajes y escapadas", txt: "Ir a un parque nacional" },
  { cat: "✈️ Viajes y escapadas", txt: "Hacer un viaje en moto o bicicleta" },
  { cat: "✈️ Viajes y escapadas", txt: "Visitar un castillo o ruinas" },
  { cat: "✈️ Viajes y escapadas", txt: "Ir a un spa de día" },
  { cat: "✈️ Viajes y escapadas", txt: "Hacer un viaje de aventura (rafting, etc.)" },
  { cat: "✈️ Viajes y escapadas", txt: "Ir a un hotel boutique" },
  { cat: "✈️ Viajes y escapadas", txt: "Visitar un faro" },
  { cat: "✈️ Viajes y escapadas", txt: "Hacer un crucero" },
  { cat: "✈️ Viajes y escapadas", txt: "Ir a un destino internacional" },
  { cat: "✈️ Viajes y escapadas", txt: "Hacer un viaje sorpresa (uno organiza todo)" },

  // ---- 🏠 EN CASA Y COTIDIANO ----
  { cat: "🏠 En casa y cotidiano", txt: "Hacer una noche de spa en casa" },
  { cat: "🏠 En casa y cotidiano", txt: "Construir un fuerte con cobijas y ver películas" },
  { cat: "🏠 En casa y cotidiano", txt: "Hacer una cena temática en casa" },
  { cat: "🏠 En casa y cotidiano", txt: "Tener una noche sin celulares" },
  { cat: "🏠 En casa y cotidiano", txt: "Hacer una lista de sueños a 5 años" },
  { cat: "🏠 En casa y cotidiano", txt: "Plantar algo juntos" },
  { cat: "🏠 En casa y cotidiano", txt: "Hacer un proyecto de DIY para la casa" },
  { cat: "🏠 En casa y cotidiano", txt: "Reorganizar un espacio juntos" },
  { cat: "🏠 En casa y cotidiano", txt: "Hacer una noche de preguntas profundas" },
  { cat: "🏠 En casa y cotidiano", txt: "Verse a los ojos por 5 minutos" },
  { cat: "🏠 En casa y cotidiano", txt: "Escribir 10 cosas que aman del otro" },
  { cat: "🏠 En casa y cotidiano", txt: "Hacer una noche de recuerdos (ver fotos viejas)" },
  { cat: "🏠 En casa y cotidiano", txt: "Cocinar el desayuno y llevárselo a la cama" },
  { cat: "🏠 En casa y cotidiano", txt: "Hacer una noche de juegos de mesa con amigos" },
  { cat: "🏠 En casa y cotidiano", txt: "Ver el mismo video al mismo tiempo desde lejos" },
  { cat: "🏠 En casa y cotidiano", txt: "Hacer una videollamada de 3 horas" },
  { cat: "🏠 En casa y cotidiano", txt: "Enviarse cartas por correo postal" },
  { cat: "🏠 En casa y cotidiano", txt: "Hacer una noche de cocina virtual juntos" },
  { cat: "🏠 En casa y cotidiano", txt: "Hacer una lista de cosas por hacer antes de los 30" },
  { cat: "🏠 En casa y cotidiano", txt: "Hacer una noche de chistes malos" },
  { cat: "🏠 En casa y cotidiano", txt: "Hacer una apuesta divertida y cumplirla" },
  { cat: "🏠 En casa y cotidiano", txt: "Hacer una noche de baile en pijama" },
  { cat: "🏠 En casa y cotidiano", txt: "Ver un documental y discutirlo" },
  { cat: "🏠 En casa y cotidiano", txt: "Hacer una noche de cocina sin receta" },
  { cat: "🏠 En casa y cotidiano", txt: "Hacer una noche de preguntas de '¿Qué preferirías?'" },
  { cat: "🏠 En casa y cotidiano", txt: "Hacer una noche de adivinanzas" },
  { cat: "🏠 En casa y cotidiano", txt: "Hacer una noche de magia o ilusionismo" },
  { cat: "🏠 En casa y cotidiano", txt: "Hacer una noche de manualidades con cosas de casa" },
  { cat: "🏠 En casa y cotidiano", txt: "Hacer una noche de cocina internacional" },
  { cat: "🏠 En casa y cotidiano", txt: "Hacer una noche de postres" },
  { cat: "🏠 En casa y cotidiano", txt: "Hacer una noche de pan casero" },
  { cat: "🏠 En casa y cotidiano", txt: "Hacer una noche de pizza" },
  { cat: "🏠 En casa y cotidiano", txt: "Hacer una noche de tacos" },
  { cat: "🏠 En casa y cotidiano", txt: "Hacer una noche de sushi" },
  { cat: "🏠 En casa y cotidiano", txt: "Hacer una noche de barbacoa" },
  { cat: "🏠 En casa y cotidiano", txt: "Hacer una noche de fondue" },
  { cat: "🏠 En casa y cotidiano", txt: "Hacer una noche de galletas" },
  { cat: "🏠 En casa y cotidiano", txt: "Hacer una noche de helado" },
  { cat: "🏠 En casa y cotidiano", txt: "Hacer una noche de chocolate caliente" },
  { cat: "🏠 En casa y cotidiano", txt: "Hacer una noche de café" },

  // ---- 🎉 CELEBRACIONES Y FECHAS ESPECIALES ----
  { cat: "🎉 Celebraciones", txt: "Celebrar un aniversario de forma especial" },
  { cat: "🎉 Celebraciones", txt: "Hacer una fiesta sorpresa" },
  { cat: "🎉 Celebraciones", txt: "Celebrar San Valentín de forma diferente" },
  { cat: "🎉 Celebraciones", txt: "Hacer una cena de gala en casa" },
  { cat: "🎉 Celebraciones", txt: "Celebrar un cumpleaños con tema" },
  { cat: "🎉 Celebraciones", txt: "Hacer una noche de premios (tipo Oscar)" },
  { cat: "🎉 Celebraciones", txt: "Celebrar el día de la amistad" },
  { cat: "🎉 Celebraciones", txt: "Hacer una noche de año nuevo juntos" },
  { cat: "🎉 Celebraciones", txt: "Celebrar Navidad de forma especial" },
  { cat: "🎉 Celebraciones", txt: "Hacer una noche de Halloween con disfraces" },
  { cat: "🎉 Celebraciones", txt: "Celebrar el día de los enamorados" },
  { cat: "🎉 Celebraciones", txt: "Hacer una noche de Acción de Gracias" },
  { cat: "🎉 Celebraciones", txt: "Celebrar un logro importante" },
  { cat: "🎉 Celebraciones", txt: "Hacer una noche de reencuentro" },
  { cat: "🎉 Celebraciones", txt: "Celebrar el día de la madre/padre juntos" },
  { cat: "🎉 Celebraciones", txt: "Hacer una noche de karaoke de cumpleaños" },
  { cat: "🎉 Celebraciones", txt: "Celebrar el primer día que se conocieron" },
  { cat: "🎉 Celebraciones", txt: "Hacer una noche de cartas y regalos" },

  // ---- 💆 BIENESTAR Y RELAX ----
  { cat: "💆 Bienestar y relax", txt: "Hacer una clase de meditación juntos" },
  { cat: "💆 Bienestar y relax", txt: "Ir a un spa de día" },
  { cat: "💆 Bienestar y relax", txt: "Hacer una noche de masajes" },
  { cat: "💆 Bienestar y relax", txt: "Hacer una clase de yoga al aire libre" },
  { cat: "💆 Bienestar y relax", txt: "Hacer una caminata consciente" },
  { cat: "💆 Bienestar y relax", txt: "Hacer una noche de té y conversación" },
  { cat: "💆 Bienestar y relax", txt: "Hacer una noche de aromaterapia" },
  { cat: "💆 Bienestar y relax", txt: "Hacer una clase de respiración" },
  { cat: "💆 Bienestar y relax", txt: "Hacer una noche de silencio y compañía" },
  { cat: "💆 Bienestar y relax", txt: "Hacer una siesta juntos" },
  { cat: "💆 Bienestar y relax", txt: "Hacer una noche de películas tranquilas" },
  { cat: "💆 Bienestar y relax", txt: "Hacer una noche de música suave" },
  { cat: "💆 Bienestar y relax", txt: "Hacer una noche de baño de tina" },
  { cat: "💆 Bienestar y relax", txt: "Hacer una noche de skincare juntos" },
  { cat: "💆 Bienestar y relax", txt: "Hacer una noche de mascarillas" },

  // ---- 🤝 ACTOS DE SERVICIO Y VOLUNTARIADO ----
  { cat: "🤝 Servicio y voluntariado", txt: "Hacer voluntariado juntos" },
  { cat: "🤝 Servicio y voluntariado", txt: "Donar ropa o cosas que ya no usen" },
  { cat: "🤝 Servicio y voluntariado", txt: "Ayudar en un refugio de animales" },
  { cat: "🤝 Servicio y voluntariado", txt: "Hacer una colecta para una causa" },
  { cat: "🤝 Servicio y voluntariado", txt: "Cocinar para alguien que lo necesite" },
  { cat: "🤝 Servicio y voluntariado", txt: "Hacer una visita a un asilo" },
  { cat: "🤝 Servicio y voluntariado", txt: "Adoptar una mascota juntos" },
  { cat: "🤝 Servicio y voluntariado", txt: "Hacer un acto de bondad aleatorio" },
  { cat: "🤝 Servicio y voluntariado", txt: "Plantar un árbol juntos" },
  { cat: "🤝 Servicio y voluntariado", txt: "Limpiar una playa o parque" },
];